name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: profile/metrics.isocalendar.halfyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year


      - name: Last 3 years calendar
        uses: lowlighter/metrics@latest
        with:
          filename: profile/metrics.plugin.calendar.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 3

      - name: Featured star list test
        uses: lowlighter/metrics@latest
        with:
          filename: profile/metrics.plugin.starlists.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 10
          plugin_starlists_only: MyCoolProjects

      - name: Featured star list languages test
        uses: lowlighter/metrics@latest
        with:
          filename: profile/metrics.plugin.starlists.languages.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: MyCoolProjects

      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=omni&hide_border=false&include_all_commits=true&count_private=true
          path: profile/my_stats.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=omni&hide_border=false&disable_animations=true
          path: profile/streak.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Generate pin card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=alrikn&repo=Zappy&theme=omni&hide_border=false
          path: profile/test_repo_pin.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/my_stats.svg profile/streak.svg profile/test_repo_pin.svg
          git diff --staged --quiet || git commit -m "Update stats cards - [Skip GitHub Action]"
          git pull --rebase origin main
          git push



