name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.isocalendar.halfyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year


      - name: Last 3 years calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 3

      - name: Featured star list test
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 10
          plugin_starlists_only: MyCoolProjects

      - name: Featured star list languages test
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.languages.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: Awesome

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: my_stats.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Generate pin card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=stats-organization&repo=github-readme-stats
          path: pin-stats-organization-github-readme-stats.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git add *.svg
          git commit -m "Update README cards" || exit 0
          git push



